export const PROJECTS = {
  'proj_8fa221': {
    name: 'Climate Reporting · US East Coast',
    seed: ['US Top Online (2024)', 'Maryland Local', 'Delaware Local', 'Virginia Local', 'DC Metro'],
    queues: [
      { id: 'Queue #1', guid: 'q1', url: 'https://reviews.mediacloud.org/review-projects/proj_8fa221/queues/a4b1f937-2c1d-46e2-b8a1-1f9c6e937201', total: 13 },
      { id: 'Queue #2', guid: 'q2', url: 'https://reviews.mediacloud.org/review-projects/proj_8fa221/queues/c8d2a043-9b66-4c4a-8e21-7d05b1227e7c', total: 10 },
      { id: 'Queue #3', guid: 'q3', url: 'https://reviews.mediacloud.org/review-projects/proj_8fa221/queues/e6f3b119-04a3-4f78-9b29-2a5f8d0aa110', total: 10 },
      { id: 'Queue #4', guid: 'q4', url: 'https://reviews.mediacloud.org/review-projects/proj_8fa221/queues/b7c4f225-32d8-4e91-a5b0-6e1a9cd44508', total: 10 },
    ],
    decisions: [
      // Queue #1 — 7 background sources (distinct from QUEUE_SOURCES the live reviewer steps through)
      { source: 'Annapolis Capital',         homepage: 'annapolis.com',              verdict: 'kept',    queue: 'Queue #1', country: 'US' },
      { source: 'Frederick News-Post',       homepage: 'fredericknewspost.com',      verdict: 'kept',    queue: 'Queue #1', country: 'US' },
      { source: 'Herald-Mail Media',         homepage: 'heraldmailmedia.com',        verdict: 'kept',    queue: 'Queue #1', country: 'US' },
      { source: 'Richmond Times-Dispatch',   homepage: 'richmond.com',               verdict: 'kept',    queue: 'Queue #1', country: 'US' },
      { source: 'Norfolk Virginian-Pilot',   homepage: 'pilotonline.com',            verdict: 'kept',    queue: 'Queue #1', country: 'US' },
      { source: 'Delaware State News',       homepage: 'newszapde.com',              verdict: 'removed', queue: 'Queue #1', country: 'US' },
      { source: 'Alexandria Gazette Packet', homepage: 'alexandriagazette.com',      verdict: 'skipped', queue: 'Queue #1', country: 'US' },
      // Queue #2 — 4 decisions
      { source: 'Maryland Reporter',         homepage: 'marylandreporter.com',       verdict: 'kept',    queue: 'Queue #2', country: 'US' },
      { source: 'DCist',                     homepage: 'dcist.com',                  verdict: 'kept',    queue: 'Queue #2', country: 'US' },
      { source: 'Bay Journal',               homepage: 'bayjournal.com',             verdict: 'kept',    queue: 'Queue #2', country: 'US' },
      { source: 'Chesapeake Bay Magazine',   homepage: 'chesapeakeboating.net',      verdict: 'skipped', queue: 'Queue #2', country: 'US' },
      // Queue #3 — 4 decisions
      { source: 'Virginia Public Radio',     homepage: 'vpm.org',                    verdict: 'kept',    queue: 'Queue #3', country: 'US' },
      { source: 'Inside Climate News',       homepage: 'insideclimatenews.org',      verdict: 'added',   queue: 'Queue #3', country: 'US' },
      { source: 'Daily Progress',            homepage: 'dailyprogress.com',          verdict: 'kept',    queue: 'Queue #3', country: 'US' },
      { source: 'Maryland Climate Daily',    homepage: 'mdclimatedaily.com',         verdict: 'removed', queue: 'Queue #3', country: 'US' },
    ],
  },

  'proj_b3c9d1': {
    name: 'Spanish-language outlets · LATAM',
    seed: ['Mexico Top Online', 'Colombia Nacional', 'Argentina Digital', 'Chile Medios', 'Peru Noticias', 'Bolivia Regional', 'Venezuela Diaspora', 'Ecuador Online'],
    queues: [
      { id: 'Queue #1', guid: 'q1', url: 'https://reviews.mediacloud.org/review-projects/proj_b3c9d1/queues/aa001122', total: 10 },
      { id: 'Queue #2', guid: 'q2', url: 'https://reviews.mediacloud.org/review-projects/proj_b3c9d1/queues/bb002233', total: 10 },
      { id: 'Queue #3', guid: 'q3', url: 'https://reviews.mediacloud.org/review-projects/proj_b3c9d1/queues/cc003344', total: 8  },
      { id: 'Queue #4', guid: 'q4', url: 'https://reviews.mediacloud.org/review-projects/proj_b3c9d1/queues/dd004455', total: 7  },
      { id: 'Queue #5', guid: 'q5', url: 'https://reviews.mediacloud.org/review-projects/proj_b3c9d1/queues/ee005566', total: 7  },
      { id: 'Queue #6', guid: 'q6', url: 'https://reviews.mediacloud.org/review-projects/proj_b3c9d1/queues/ff006677', total: 8  },
    ],
    decisions: [
      { source: 'El Universal',           homepage: 'eluniversal.com.mx',     verdict: 'kept',    queue: 'Queue #1', country: 'Mexico' },
      { source: 'La Jornada',             homepage: 'jornada.com.mx',         verdict: 'kept',    queue: 'Queue #1', country: 'Mexico' },
      { source: 'El Financiero',          homepage: 'elfinanciero.com.mx',    verdict: 'kept',    queue: 'Queue #1', country: 'Mexico' },
      { source: 'Noticias Yucatán',      homepage: 'noticiastucatan.com.mx',  verdict: 'removed', queue: 'Queue #1', country: 'Mexico' },
      { source: 'El Colombiano',          homepage: 'elcolombiano.com',       verdict: 'kept',    queue: 'Queue #2', country: 'Colombia' },
      { source: 'El Espectador',          homepage: 'elespectador.com',       verdict: 'kept',    queue: 'Queue #2', country: 'Colombia' },
      { source: 'Semana',                 homepage: 'semana.com',             verdict: 'kept',    queue: 'Queue #2', country: 'Colombia' },
      { source: 'ACI Prensa',             homepage: 'aciprensa.com',          verdict: 'removed', queue: 'Queue #2', country: 'Peru' },
      { source: 'La Nación Argentina',   homepage: 'lanacion.com.ar',         verdict: 'kept',    queue: 'Queue #3', country: 'Argentina' },
      { source: 'Infobae',                homepage: 'infobae.com',            verdict: 'kept',    queue: 'Queue #3', country: 'Argentina' },
      { source: 'Clarín',                homepage: 'clarin.com',              verdict: 'kept',    queue: 'Queue #3', country: 'Argentina' },
      { source: 'El Mercurio',            homepage: 'emol.com',               verdict: 'kept',    queue: 'Queue #4', country: 'Chile' },
      { source: 'La Tercera',             homepage: 'latercera.com',          verdict: 'kept',    queue: 'Queue #4', country: 'Chile' },
      { source: 'El Comercio Perú',      homepage: 'elcomercio.pe',           verdict: 'kept',    queue: 'Queue #5', country: 'Peru' },
      { source: 'RPP Noticias',           homepage: 'rpp.pe',                 verdict: 'kept',    queue: 'Queue #5', country: 'Peru' },
      { source: 'La Razón Bolivia',      homepage: 'la-razon.com',            verdict: 'kept',    queue: 'Queue #6', country: 'Bolivia' },
      { source: 'Venezuela Wire',         homepage: 'venezuelawire.com',      verdict: 'skipped', queue: 'Queue #6', country: 'Venezuela' },
      { source: 'El Universo Ecuador',   homepage: 'eluniverso.com',          verdict: 'kept',    queue: 'Queue #6', country: 'Ecuador' },
      { source: 'La Hora Ecuador',       homepage: 'lahora.com.ec',           verdict: 'added',   queue: 'Queue #6', country: 'Ecuador' },
    ],
  },

  'proj_a7f3e2': {
    name: 'Top Online · Brazil 2025',
    seed: ['Brazil Top Online (2025)', 'Rio de Janeiro News', 'São Paulo Digital'],
    queues: [
      { id: 'Queue #1', guid: 'q1', url: 'https://reviews.mediacloud.org/review-projects/proj_a7f3e2/queues/aaa11111', total: 10 },
      { id: 'Queue #2', guid: 'q2', url: 'https://reviews.mediacloud.org/review-projects/proj_a7f3e2/queues/bbb22222', total: 9  },
      { id: 'Queue #3', guid: 'q3', url: 'https://reviews.mediacloud.org/review-projects/proj_a7f3e2/queues/ccc33333', total: 8  },
    ],
    decisions: [
      { source: 'Folha de S.Paulo',       homepage: 'folha.uol.com.br',             verdict: 'kept',    queue: 'Queue #1', country: 'Brazil' },
      { source: 'G1 / Globo',            homepage: 'g1.globo.com',                  verdict: 'kept',    queue: 'Queue #1', country: 'Brazil' },
      { source: 'UOL Notícias',          homepage: 'noticias.uol.com.br',            verdict: 'kept',    queue: 'Queue #1', country: 'Brazil' },
      { source: 'O Globo',                homepage: 'oglobo.globo.com',              verdict: 'kept',    queue: 'Queue #1', country: 'Brazil' },
      { source: 'Brasil 247',             homepage: 'brasil247.com',                 verdict: 'skipped', queue: 'Queue #1', country: 'Brazil' },
      { source: 'Agora SP',              homepage: 'agora.folha.uol.com.br',         verdict: 'removed', queue: 'Queue #2', country: 'Brazil' },
      { source: 'Terra',                 homepage: 'terra.com.br',                   verdict: 'removed', queue: 'Queue #2', country: 'Brazil' },
      { source: 'Correio Braziliense',   homepage: 'correiobraziliense.com.br',      verdict: 'kept',    queue: 'Queue #2', country: 'Brazil' },
      { source: 'Estado de Minas',        homepage: 'em.com.br',                     verdict: 'kept',    queue: 'Queue #2', country: 'Brazil' },
      { source: 'Poder360',              homepage: 'poder360.com.br',                verdict: 'added',   queue: 'Queue #3', country: 'Brazil' },
      { source: 'The Brazilian Report',  homepage: 'brazilian.report',               verdict: 'added',   queue: 'Queue #3', country: 'Brazil' },
      { source: 'Época Negócios',        homepage: 'epocanegocios.globo.com',        verdict: 'kept',    queue: 'Queue #3', country: 'Brazil' },
      { source: 'Congresso em Foco',     homepage: 'congressoemfoco.uol.com.br',     verdict: 'kept',    queue: 'Queue #3', country: 'Brazil' },
    ],
  },

  'proj_d4c5b6': {
    name: 'AI-generated content sweep',
    seed: ['Flagged Sources · 2025', 'AI Monitoring List'],
    queues: [
      { id: 'Queue #1', guid: 'q1', url: 'https://reviews.mediacloud.org/review-projects/proj_d4c5b6/queues/ddd44444', total: 10 },
      { id: 'Queue #2', guid: 'q2', url: 'https://reviews.mediacloud.org/review-projects/proj_d4c5b6/queues/eee55555', total: 10 },
    ],
    decisions: [
      { source: 'Associated Press',        homepage: 'apnews.com',            verdict: 'kept',    queue: 'Queue #1', country: 'US' },
      { source: 'Reuters',                 homepage: 'reuters.com',           verdict: 'kept',    queue: 'Queue #1', country: 'UK' },
      { source: 'NewsBreak',               homepage: 'newsbreak.com',         verdict: 'removed', queue: 'Queue #1', country: 'US' },
      { source: 'Automated Insights Feed', homepage: 'automatedinsights.com', verdict: 'removed', queue: 'Queue #1', country: 'US' },
      { source: 'LocalSmart Media',        homepage: 'localsmartmedia.com',   verdict: 'removed', queue: 'Queue #1', country: 'US' },
      { source: 'Patch Media',             homepage: 'patch.com',             verdict: 'skipped', queue: 'Queue #1', country: 'US' },
      { source: 'The Information',         homepage: 'theinformation.com',    verdict: 'kept',    queue: 'Queue #2', country: 'US' },
      { source: 'Bloomberg',               homepage: 'bloomberg.com',         verdict: 'kept',    queue: 'Queue #2', country: 'US' },
      { source: 'Heliogen News',           homepage: 'heliogennews.com',      verdict: 'removed', queue: 'Queue #2', country: 'US' },
      { source: 'AI Reporter',             homepage: 'aireporter.ai',         verdict: 'removed', queue: 'Queue #2', country: 'US' },
      { source: 'Synth Daily',             homepage: 'synthdaily.news',       verdict: 'removed', queue: 'Queue #2', country: 'US' },
      { source: 'MIT Technology Review',   homepage: 'technologyreview.com',  verdict: 'added',   queue: 'Queue #2', country: 'US' },
    ],
  },

  'proj_f1e2a3': {
    name: 'Public broadcasters · EU',
    seed: ['EU Public Broadcasters', 'BBC Network', 'ARD & ZDF', 'France Télévisions'],
    queues: [
      { id: 'Queue #1', guid: 'q1', url: 'https://reviews.mediacloud.org/review-projects/proj_f1e2a3/queues/fff11111', total: 6 },
      { id: 'Queue #2', guid: 'q2', url: 'https://reviews.mediacloud.org/review-projects/proj_f1e2a3/queues/fff22222', total: 5 },
      { id: 'Queue #3', guid: 'q3', url: 'https://reviews.mediacloud.org/review-projects/proj_f1e2a3/queues/fff33333', total: 6 },
    ],
    decisions: [
      { source: 'BBC News',            homepage: 'bbc.co.uk/news',    verdict: 'kept',    queue: 'Queue #1', country: 'UK' },
      { source: 'BBC World Service',   homepage: 'bbc.co.uk',         verdict: 'kept',    queue: 'Queue #1', country: 'UK' },
      { source: 'ARD',                 homepage: 'ard.de',            verdict: 'kept',    queue: 'Queue #1', country: 'Germany' },
      { source: 'ZDF',                 homepage: 'zdf.de',            verdict: 'kept',    queue: 'Queue #1', country: 'Germany' },
      { source: 'SVT',                 homepage: 'svt.se',            verdict: 'kept',    queue: 'Queue #1', country: 'Sweden' },
      { source: 'DR',                  homepage: 'dr.dk',             verdict: 'kept',    queue: 'Queue #1', country: 'Denmark' },
      { source: 'France 24',           homepage: 'france24.com',      verdict: 'kept',    queue: 'Queue #2', country: 'France' },
      { source: 'France Télévisions', homepage: 'francetvinfo.fr',    verdict: 'kept',    queue: 'Queue #2', country: 'France' },
      { source: 'Radio France',        homepage: 'radiofrance.fr',    verdict: 'kept',    queue: 'Queue #2', country: 'France' },
      { source: 'NOS',                 homepage: 'nos.nl',            verdict: 'kept',    queue: 'Queue #2', country: 'Netherlands' },
      { source: 'Yle',                 homepage: 'yle.fi',            verdict: 'kept',    queue: 'Queue #2', country: 'Finland' },
      { source: 'RAI News',            homepage: 'rainews.it',        verdict: 'kept',    queue: 'Queue #3', country: 'Italy' },
      { source: 'TVE',                 homepage: 'rtve.es',           verdict: 'kept',    queue: 'Queue #3', country: 'Spain' },
      { source: 'RTP',                 homepage: 'rtp.pt',            verdict: 'kept',    queue: 'Queue #3', country: 'Portugal' },
      { source: 'ORF',                 homepage: 'orf.at',            verdict: 'kept',    queue: 'Queue #3', country: 'Austria' },
      { source: 'ERT',                 homepage: 'ert.gr',            verdict: 'skipped', queue: 'Queue #3', country: 'Greece' },
      { source: 'LTV',                 homepage: 'ltv.lsm.lv',       verdict: 'removed', queue: 'Queue #3', country: 'Latvia' },
    ],
  },

  'proj_c2d3e4': {
    name: 'Top Online · Brazil 2024',
    seed: ['Brazil Top Online (2024)', 'São Paulo Digital'],
    queues: [
      { id: 'Queue #1', guid: 'q1', url: 'https://reviews.mediacloud.org/review-projects/proj_c2d3e4/queues/ccc11111', total: 6 },
      { id: 'Queue #2', guid: 'q2', url: 'https://reviews.mediacloud.org/review-projects/proj_c2d3e4/queues/ccc22222', total: 6 },
    ],
    decisions: [
      { source: 'Folha de S.Paulo',  homepage: 'folha.uol.com.br',          verdict: 'kept',    queue: 'Queue #1', country: 'Brazil' },
      { source: 'G1',                homepage: 'g1.globo.com',              verdict: 'kept',    queue: 'Queue #1', country: 'Brazil' },
      { source: 'UOL',               homepage: 'uol.com.br',                verdict: 'kept',    queue: 'Queue #1', country: 'Brazil' },
      { source: 'Exame',             homepage: 'exame.com',                 verdict: 'kept',    queue: 'Queue #1', country: 'Brazil' },
      { source: 'R7',                homepage: 'r7.com',                    verdict: 'removed', queue: 'Queue #1', country: 'Brazil' },
      { source: 'Veja',              homepage: 'veja.abril.com.br',         verdict: 'kept',    queue: 'Queue #1', country: 'Brazil' },
      { source: 'Band News',         homepage: 'band.uol.com.br/noticias',  verdict: 'kept',    queue: 'Queue #2', country: 'Brazil' },
      { source: 'CNN Brasil',        homepage: 'cnnbrasil.com.br',          verdict: 'kept',    queue: 'Queue #2', country: 'Brazil' },
      { source: 'GaúchaZH',        homepage: 'gauchazh.clicrbs.com.br',    verdict: 'kept',    queue: 'Queue #2', country: 'Brazil' },
      { source: 'Correio do Povo',   homepage: 'correiodopovo.com.br',      verdict: 'kept',    queue: 'Queue #2', country: 'Brazil' },
      { source: 'Agência Brasil',    homepage: 'agenciabrasil.ebc.com.br',  verdict: 'added',   queue: 'Queue #2', country: 'Brazil' },
      { source: 'Terra Notícias',   homepage: 'terra.com.br',               verdict: 'removed', queue: 'Queue #2', country: 'Brazil' },
    ],
  },
};

export const MOCK = {
  source: {
    title: 'The Capital Gazette',
    homepage: 'capitalgazette.com',
    language: 'English',
    country: 'United States',
    state: 'Maryland',
    priorComment: {
      text: 'Looks like a local outlet, but a lot of the recent articles are syndicated wire copy. Flagging for a second look before we keep it.',
      when: 'left 2 days ago',
    },
  },
  project: null, // now derived from PROJECTS dynamically
};
